name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "@all-contributions add @${{ github.event.pull_request.user.login }}  for code"
