# This is a basic workflow to help you get started with Actions

name: Auto Add Contributions

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  comment:
    permissions: 
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add comment to PR
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          @all-contributors add @${{ github.event.pull_request_target.user.login }} as a contributor for code
    
